package:
  name: dgllife{{ environ.get('APP_PACKAGE_SUFFIX', '') }}
  version: "0.2.6"

source:
  url: https://files.pythonhosted.org/packages/89/f3/04509470ce7fad6d647c8b41ffff8984b7691260eb78b305997104b09ebc/dgllife-0.2.6.tar.gz
  sha256: 255761bfdf8bfcdef79abb7b9b143a62d11ff10297f7f2e6cecbcb41b5609c76

channels:
  - defaults
  - conda-forge

requirements:
  build:
    - python {{ python }}
    - setuptools
    - cmake
    - git
    - cython
  run:
    - python
    - requests
    - scikit-learn
    - pandas
    - tqdm
    - numpy
    - scipy
    - networkx

about:
  license: Apache