package:
  name: dgllife{{ environ.get('APP_PACKAGE_SUFFIX', '') }}
  version: "0.2.4"

source:
  url: https://files.pythonhosted.org/packages/94/fc/931ccf09805bf1a4e66b7ce75ed7756769c5824c9e0bb3b7ce18c82e1a99/dgllife-0.2.4.tar.gz
  sha256: b893669f5fc83d77af64d1d7b3a95b5ca37f5a22d00e36ff4d4bcb636a5bae39

channels:
  - defaults
  - conda-forge

requirements:
  build:
    - python {{ python }}
    - setuptools
    - cmake
    - git
    - cython
  run:
    - python
    - requests
    - scikit-learn
    - pandas
    - tqdm
    - numpy
    - scipy
    - networkx

about:
  license: Apache