package:
  name: dgllife{{ environ.get('APP_PACKAGE_SUFFIX', '') }}
  version: "0.2.7"

source:
  url: https://files.pythonhosted.org/packages/04/f1/08bed2f6e9f869d8cd4a101978c5ec202769554d8baf44e1c39f80a40cf5/dgllife-0.2.7.tar.gz
  sha256: acd23be4c3810c2dbfd4ec2bade58d552f6b81452a89e1ffe35a34e846327bd2

channels:
  - defaults
  - conda-forge

requirements:
  build:
    - python {{ python }}
    - setuptools
    - cmake
    - git
    - cython
  run:
    - python
    - requests
    - scikit-learn
    - pandas
    - tqdm
    - numpy
    - scipy
    - networkx

about:
  license: Apache