name: pytorch-ci
channels:
  - defaults
  - rdkit
dependencies:
  - python=3.6.9
  - pip
  - pip:
    - torch
    - torchvision
    - pytest
    - nose
    - numpy
    - cython
    - scipy
    - networkx
    - matplotlib
    - nltk
    - requests[security]
    - tqdm
    - scikit-learn
    - pandas
  - rdkit==2018.09.3
